# ===========================================
# 测试环境部署配置
# ===========================================
version: '3.8'

include:
  - ../compose/base.yml
  - ../compose/vector.yml
  - ../compose/monitoring.yml
  - ../compose/services/api-server.yml
  - ../compose/services/workers.yml
  - ../compose/services/pdf-validator.yml
  - ../compose/services/llm-service.yml

services:
  # 覆盖基础服务配置以适应测试环境
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'

  minio:
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.15'

  # 测试环境专用工具
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${COMPOSE_PROJECT_NAME:-moonshot-staging}-portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - moonshot-network
    profiles: ["tools"]

volumes:
  portainer_data:
    name: ${COMPOSE_PROJECT_NAME}_portainer_data

networks:
  moonshot-network:
    name: ${NETWORK_NAME:-moonshot-staging}
    driver: bridge