# ===========================================
# 本地开发环境部署配置
# ===========================================

include:
  - ../compose/base.yml
  - ../compose/services/api-server.yml
  - ../compose/services/workers.yml
  - ../compose/services/pdf-validator.yml
  - ../compose/services/llm-service.yml

services:
  # 本地开发专用服务
  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME:-moonshot-local}-adminer
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - moonshot-network
    profiles: ["dev", "tools"]

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: ${COMPOSE_PROJECT_NAME:-moonshot-local}-redis-commander
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: "local:redis:6379"
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    depends_on:
      - redis
    networks:
      - moonshot-network
    profiles: ["dev", "tools"]

networks:
  moonshot-network:
    name: ${NETWORK_NAME:-moonshot-local}
    driver: bridge