# ===========================================
# 网关和代理服务 - Nginx
# ===========================================
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "80:80"
      - "${SSL_ENABLED:+443:443}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ${SSL_ENABLED:+./nginx/ssl:/etc/nginx/ssl:ro}
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
    depends_on:
      - api-server
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - moonshot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  nginx_cache:
    name: ${COMPOSE_PROJECT_NAME}_nginx_cache
  nginx_logs:
    name: ${COMPOSE_PROJECT_NAME}_nginx_logs

