# ===========================================
# 向量数据库服务 - Milvus, etcd
# ===========================================
version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: ${COMPOSE_PROJECT_NAME}-etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:${ETCD_PORT} -listen-client-urls http://0.0.0.0:${ETCD_PORT} --data-dir /etcd
    ports:
      - "${ETCD_EXTERNAL_PORT:-23379}:${ETCD_PORT:-2379}"
    volumes:
      - etcd_data:/etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - moonshot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 注意：这里的minio是向量数据库专用的，端口不同避免冲突
  minio-vector:
    image: minio/minio:latest
    container_name: ${COMPOSE_PROJECT_NAME}-minio-vector
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: minio server /minio_data
    volumes:
      - minio_vector_data:/minio_data
    networks:
      - moonshot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  milvus:
    image: milvusdb/milvus:latest
    container_name: ${COMPOSE_PROJECT_NAME}-milvus
    platform: linux/arm64
    ports:
      - "${MILVUS_EXTERNAL_PORT:-29530}:${MILVUS_PORT:-19530}"
      - "${MILVUS_HTTP_EXTERNAL_PORT:-29091}:${MILVUS_HTTP_PORT:-9091}"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      ETCD_ENDPOINTS: etcd:${ETCD_PORT:-2379}
      MINIO_ADDRESS: minio-vector:9000
    depends_on:
      - etcd
      - minio-vector
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MILVUS_HTTP_PORT:-9091}/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - moonshot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  etcd_data:
    name: ${COMPOSE_PROJECT_NAME}_etcd_data
  minio_vector_data:
    name: ${COMPOSE_PROJECT_NAME}_minio_vector_data
  milvus_data:
    name: ${COMPOSE_PROJECT_NAME}_milvus_data

